### ISSUE TITLE
Issue on OpenBSD

### ISSUE THREAD

**Issue by souperdoupe** [ldx/DBdownload#20]
Hi, thanks for writing this script. I love the idea and simplicity behind it and was hoping it could work on openbsd for maximum portability.  My only issue so far is this:

$ python2.7 dbdownload.py
2018-03-25 14:53:36,917 *** DBdownload v0.0 starting up ***
2018-03-25 14:53:36,920 loaded token
2018-03-25 14:53:36,920 loaded delta cursor
2018-03-25 14:53:36,920 loaded local tree
Traceback (most recent call last):
  File "dbdownload.py", line 534, in <module>
    main()
  File "dbdownload.py", line 524, in main
    options['interval'], options['exec'])
  File "dbdownload.py", line 90, in __init__
    key, secret = decode_dropbox_key(APP_KEY)
  File "dbdownload.py", line 39, in decode_dropbox_key
    key, secret = key.split('|')
ValueError: need more than 1 value to unpack

Any ideas about how to solve this?

**Comment by ldx** [comment]
Did you set your APP_KEY?
